# Generated by Django 3.0.6 on 2020-05-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='transcription',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='word',
            name='translation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
