# Generated by Django 3.0.6 on 2020-05-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0006_auto_20200512_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
