# Generated by Django 3.0.6 on 2020-05-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0007_dictionary_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
