# Generated by Django 3.0.6 on 2020-05-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0009_remove_word_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={},
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='date_create',
        ),
    ]
