# Generated by Django 3.0.6 on 2020-05-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0012_auto_20200512_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='slug',
        ),
    ]
