# Generated by Django 3.0.6 on 2020-05-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0017_auto_20200518_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
