# Generated by Django 3.0.6 on 2020-05-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0018_dictionary_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
