# Generated by Django 3.0.6 on 2020-05-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
