# Generated by Django 3.0.6 on 2020-05-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0003_auto_20200518_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
